spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_selection?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC%2B8
    username: root
    password: 110211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  hibernate:
    ddl-auto: update
    database: MYSQL
    show-sql: true